# fly.toml app configuration file generated for stormful on 2024-10-18T23:19:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stormful'
primary_region = 'cdg'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
